export App from './App/App';
export Chat from './Chat/Chat';
export Home from './Home/Home';
export Widgets from './Widgets/Widgets';
export About from './About/About';
export Login from './Login/Login';
export LoginSuccess from './LoginSuccess/LoginSuccess';
export Survey from './Survey/Survey';
export NotFound from './NotFound/NotFound';
export SchemaUpload from './SchemaUpload/SchemaUpload';
export SchemasList from './SchemasList/SchemasList';
export Schema from './Schema/Schema'
export Visualizer from './Visualizer/Visualizer';
export XMLVisualizer from './Visualizer/XMLVisualizer';