import React, {Component} from 'react';
import Graph from './Graph';

export default class Visualizer extends Component {
  state = {
    file: {},
    isShown: false
  };

  fetchFile = () => {
    console.log('start fetch file');
    const textExample = {
      edges:
[ { from: 'AircraftID',
    to: 'DatatypeProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'data-property', 'resource' ] },
  { from: 'Cairo_02E',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'Almaza_A2',
    to: 'Gate',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_B1',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'GatePassengerCapacity',
    to: 'Gate',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'AirfieldID',
    to: 'Airfield',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'MaximumSpeed',
    to: 'integer',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_A1',
    to: 'A330',
    label: 'AirportOntology:CompatibleAircraftType',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_A2',
    to: 'A2',
    label: 'AirportOntology:GateID',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'AirBus_KMN20',
    to: 'WideBody',
    label: 'AirportOntology:AircraftClass',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'AirBus_SKU10',
    to: '4',
    label: 'AirportOntology:EngineCount',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_A',
    to: 'Almaza_HELA',
    label: 'AirportOntology:GroundSurfaceIsPartOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_02E',
    to: 'Cairo_K',
    label: 'AirportOntology:HasExitTo',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_HELA',
    to: 'Almaza_A',
    label: 'AirportOntology:ConsistOfGroundSurface',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_CAI',
    to: '300',
    label: 'AirportOntology:Elevation',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_HELA',
    to: '200',
    label: 'AirportOntology:Elevation',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Elevation',
    to: 'DatatypeProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'data-property', 'resource' ] },
  { from: 'Airfield',
    to: 'Class',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'class', 'resource' ] },
  { from: 'Cairo_C1',
    to: 'Gate',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_C1',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'Gate',
    to: 'Class',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'class', 'resource' ] },
  { from: 'CompatibleAircraftType',
    to: 'DatatypeProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'data-property', 'resource' ] },
  { from: 'CompatibleWith',
    to: 'ObjectProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'object-property', 'resource' ] },
  { from: 'Boeing_UWD20',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'Boeing_UWD20',
    to: 'Aircraft',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'GateID',
    to: 'DatatypeProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'data-property', 'resource' ] },
  { from: 'GateIsPartOf',
    to: 'ObjectProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'object-property', 'resource' ] },
  { from: 'Cairo_CAI',
    to: 'Airfield',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_CAI',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'GatePassengerCapacity',
    to: 'DatatypeProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'data-property', 'resource' ] },
  { from: 'AircraftClass',
    to: 'DatatypeProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'data-property', 'resource' ] },
  { from: 'Aircraft',
    to: 'Class',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'class', 'resource' ] },
  { from: 'AirBus_SKU10',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'AirBus_SKU10',
    to: 'Aircraft',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'AircraftPassengerCapacity',
    to: 'DatatypeProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'data-property', 'resource' ] },
  { from: 'AircraftType',
    to: 'DatatypeProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'data-property', 'resource' ] },
  { from: 'EngineCount',
    to: 'DatatypeProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'data-property', 'resource' ] },
  { from: 'IsLocatedIn',
    to: 'ObjectProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'object-property', 'resource' ] },
  { from: 'Almaza_05C',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'Almaza_05C',
    to: 'Runway',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Manufacturer',
    to: 'DatatypeProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'data-property', 'resource' ] },
  { from: 'MaximumSpeed',
    to: 'DatatypeProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'data-property', 'resource' ] },
  { from: 'Almaza_A',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'Almaza_A',
    to: 'Taxiway',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Taxiway',
    to: 'Class',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'class', 'resource' ] },
  { from: 'GroundSurfaceIsPartOf',
    to: 'ObjectProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'object-property', 'resource' ] },
  { from: 'Almaza_HELA',
    to: 'Airfield',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_HELA',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'GroundSurfaceName',
    to: 'DatatypeProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'data-property', 'resource' ] },
  { from: 'HasEntranceTo',
    to: 'ObjectProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'object-property', 'resource' ] },
  { from: 'Almaza_14D',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'Almaza_14D',
    to: 'Runway',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'MaintenanceStatus',
    to: 'DatatypeProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'data-property', 'resource' ] },
  { from: 'Cairo_02E',
    to: 'Runway',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Runway',
    to: 'Class',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'class', 'resource' ] },
  { from: 'GroundType',
    to: 'DatatypeProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'data-property', 'resource' ] },
  { from: 'HasExitTo',
    to: 'ObjectProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'object-property', 'resource' ] },
  { from: 'Cairo_K',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'Cairo_K',
    to: 'Taxiway',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Length',
    to: 'DatatypeProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'data-property', 'resource' ] },
  { from: 'Cairo_B',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'Cairo_B',
    to: 'Taxiway',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_06D',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'Cairo_06D',
    to: 'Runway',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Contain',
    to: 'ObjectProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'object-property', 'resource' ] },
  { from: 'Airport',
    to: 'Class',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'class', 'resource' ] },
  { from: 'Cairo_B2',
    to: 'Gate',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_B2',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'AirportOntology',
    to: 'Ontology',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'CairoInternationalAirport',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'CairoInternationalAirport',
    to: 'Airport',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'AirportName',
    to: 'DatatypeProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'data-property', 'resource' ] },
  { from: 'Almaza_A2',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'AirBus_KMN20',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'AirBus_KMN20',
    to: 'Aircraft',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'AirfieldID',
    to: 'DatatypeProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'data-property', 'resource' ] },
  { from: 'ConsistOfGate',
    to: 'ObjectProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'object-property', 'resource' ] },
  { from: 'Almaza_A1',
    to: 'Gate',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_A1',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'ConsistOfGroundSurface',
    to: 'ObjectProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'object-property', 'resource' ] },
  { from: 'Almaza_M',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'Almaza_M',
    to: 'Taxiway',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'UsageType',
    to: 'DatatypeProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'data-property', 'resource' ] },
  { from: 'GroundSurface',
    to: 'Class',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'class', 'resource' ] },
  { from: '_:94',
    to: 'Datatype',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: '_:96',
    to: 'List',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: '_:99',
    to: 'List',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_B1',
    to: 'Gate',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Boeing_STU30',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'Boeing_STU30',
    to: 'Aircraft',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'LocationOf',
    to: 'ObjectProperty',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'object-property', 'resource' ] },
  { from: 'AlmazaAirport',
    to: 'NamedIndividual',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'individual', 'resource' ] },
  { from: 'AlmazaAirport',
    to: 'Airport',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: '_:117',
    to: 'Datatype',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: '_:118',
    to: 'List',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: '_:119',
    to: 'List',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: '_:128',
    to: 'Datatype',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: '_:129',
    to: 'List',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: '_:131',
    to: 'List',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: '_:133',
    to: 'List',
    label: 'rdf:type',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Elevation',
    to: 'Airfield',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'CompatibleAircraftType',
    to: 'Gate',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'CompatibleWith',
    to: 'Gate',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'GateID',
    to: 'Gate',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'GateIsPartOf',
    to: 'Gate',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'AircraftClass',
    to: 'Aircraft',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'AircraftID',
    to: 'Aircraft',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'AircraftPassengerCapacity',
    to: 'Aircraft',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'AircraftType',
    to: 'Aircraft',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'EngineCount',
    to: 'Aircraft',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'IsLocatedIn',
    to: 'Aircraft',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Manufacturer',
    to: 'Aircraft',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'MaximumSpeed',
    to: 'Aircraft',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'GroundSurfaceIsPartOf',
    to: 'GroundSurface',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'GroundSurfaceName',
    to: 'GroundSurface',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'HasEntranceTo',
    to: 'Taxiway',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'MaintenanceStatus',
    to: 'Taxiway',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'GroundType',
    to: 'Runway',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'HasExitTo',
    to: 'Runway',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Length',
    to: 'Runway',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Contain',
    to: 'Airport',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'AirportName',
    to: 'Airport',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'ConsistOfGate',
    to: 'Airfield',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'ConsistOfGroundSurface',
    to: 'Airfield',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'UsageType',
    to: 'Airfield',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'LocationOf',
    to: 'GroundSurface',
    label: 'rdfs:domain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Elevation',
    to: 'integer',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'CompatibleAircraftType',
    to: 'string',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'CompatibleWith',
    to: 'Aircraft',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'GateID',
    to: 'string',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'GateIsPartOf',
    to: 'Airfield',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'GatePassengerCapacity',
    to: 'integer',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'AircraftClass',
    to: 'string',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'AircraftID',
    to: 'string',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'AircraftPassengerCapacity',
    to: 'integer',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'AircraftType',
    to: 'string',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'EngineCount',
    to: 'integer',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'IsLocatedIn',
    to: 'GroundSurface',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Manufacturer',
    to: 'string',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'GroundSurfaceIsPartOf',
    to: 'Airfield',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'GroundSurfaceName',
    to: 'string',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'HasEntranceTo',
    to: 'Runway',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'MaintenanceStatus',
    to: '_:117',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'blanknode', 'resource' ] },
  { from: 'GroundType',
    to: '_:94',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'blanknode', 'resource' ] },
  { from: 'HasExitTo',
    to: 'Taxiway',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Length',
    to: 'integer',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Contain',
    to: 'Airfield',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'AirportName',
    to: 'string',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'AirfieldID',
    to: 'string',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'ConsistOfGate',
    to: 'Gate',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'ConsistOfGroundSurface',
    to: 'GroundSurface',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'UsageType',
    to: '_:128',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'blanknode', 'resource' ] },
  { from: 'LocationOf',
    to: 'Aircraft',
    label: 'rdfs:range',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_C1',
    to: 'Boeing787',
    label: 'AirportOntology:CompatibleAircraftType',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_B2',
    to: 'A320',
    label: 'AirportOntology:CompatibleAircraftType',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_A2',
    to: 'A330',
    label: 'AirportOntology:CompatibleAircraftType',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_A2',
    to: 'A380',
    label: 'AirportOntology:CompatibleAircraftType',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_A1',
    to: 'A320',
    label: 'AirportOntology:CompatibleAircraftType',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_A1',
    to: 'A380',
    label: 'AirportOntology:CompatibleAircraftType',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_B1',
    to: 'Boeing787',
    label: 'AirportOntology:CompatibleAircraftType',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_B1',
    to: 'Boeing767',
    label: 'AirportOntology:CompatibleAircraftType',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_B1',
    to: 'Boeing737',
    label: 'AirportOntology:CompatibleAircraftType',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_C1',
    to: 'Boeing_UWD20',
    label: 'AirportOntology:CompatibleWith',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_A2',
    to: 'AirBus_SKU10',
    label: 'AirportOntology:CompatibleWith',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_A2',
    to: 'AirBus_KMN20',
    label: 'AirportOntology:CompatibleWith',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_A1',
    to: 'AirBus_SKU10',
    label: 'AirportOntology:CompatibleWith',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_A1',
    to: 'AirBus_KMN20',
    label: 'AirportOntology:CompatibleWith',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_B1',
    to: 'Boeing_UWD20',
    label: 'AirportOntology:CompatibleWith',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_B1',
    to: 'Boeing_STU30',
    label: 'AirportOntology:CompatibleWith',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_C1',
    to: 'C1',
    label: 'AirportOntology:GateID',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_B2',
    to: 'B2',
    label: 'AirportOntology:GateID',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_A1',
    to: 'A1',
    label: 'AirportOntology:GateID',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_B1',
    to: 'B1',
    label: 'AirportOntology:GateID',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_C1',
    to: 'Cairo_CAI',
    label: 'AirportOntology:GateIsPartOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_B2',
    to: 'Cairo_CAI',
    label: 'AirportOntology:GateIsPartOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_A2',
    to: 'Almaza_HELA',
    label: 'AirportOntology:GateIsPartOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_A1',
    to: 'Almaza_HELA',
    label: 'AirportOntology:GateIsPartOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_B1',
    to: 'Cairo_CAI',
    label: 'AirportOntology:GateIsPartOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_C1',
    to: '100',
    label: 'AirportOntology:GatePassengerCapacity',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_B2',
    to: '300',
    label: 'AirportOntology:GatePassengerCapacity',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_A2',
    to: '300',
    label: 'AirportOntology:GatePassengerCapacity',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_A1',
    to: '350',
    label: 'AirportOntology:GatePassengerCapacity',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_B1',
    to: '150',
    label: 'AirportOntology:GatePassengerCapacity',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Boeing_UWD20',
    to: 'NarrowBody',
    label: 'AirportOntology:AircraftClass',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'AirBus_SKU10',
    to: 'WideBody',
    label: 'AirportOntology:AircraftClass',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Boeing_STU30',
    to: 'NarrowBody',
    label: 'AirportOntology:AircraftClass',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Boeing_UWD20',
    to: 'UWD20',
    label: 'AirportOntology:AircraftID',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'AirBus_SKU10',
    to: 'SKU10',
    label: 'AirportOntology:AircraftID',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'AirBus_KMN20',
    to: 'KMN20',
    label: 'AirportOntology:AircraftID',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Boeing_STU30',
    to: 'STU30',
    label: 'AirportOntology:AircraftID',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Boeing_UWD20',
    to: '100',
    label: 'AirportOntology:AircraftPassengerCapacity',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'AirBus_SKU10',
    to: '200',
    label: 'AirportOntology:AircraftPassengerCapacity',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'AirBus_KMN20',
    to: '300',
    label: 'AirportOntology:AircraftPassengerCapacity',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Boeing_STU30',
    to: '150',
    label: 'AirportOntology:AircraftPassengerCapacity',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Boeing_UWD20',
    to: 'Boeing787',
    label: 'AirportOntology:AircraftType',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'AirBus_SKU10',
    to: 'A330',
    label: 'AirportOntology:AircraftType',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'AirBus_KMN20',
    to: 'A380',
    label: 'AirportOntology:AircraftType',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Boeing_STU30',
    to: 'Boeing737',
    label: 'AirportOntology:AircraftType',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Boeing_UWD20',
    to: '2',
    label: 'AirportOntology:EngineCount',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'AirBus_KMN20',
    to: '4',
    label: 'AirportOntology:EngineCount',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Boeing_STU30',
    to: '2',
    label: 'AirportOntology:EngineCount',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Boeing_UWD20',
    to: 'Cairo_K',
    label: 'AirportOntology:IsLocatedIn',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'AirBus_SKU10',
    to: 'Almaza_05C',
    label: 'AirportOntology:IsLocatedIn',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'AirBus_KMN20',
    to: 'Almaza_05C',
    label: 'AirportOntology:IsLocatedIn',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Boeing_STU30',
    to: 'Cairo_06D',
    label: 'AirportOntology:IsLocatedIn',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Boeing_UWD20',
    to: 'Boeing',
    label: 'AirportOntology:Manufacturer',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'AirBus_SKU10',
    to: 'AirBus',
    label: 'AirportOntology:Manufacturer',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'AirBus_KMN20',
    to: 'AirBus',
    label: 'AirportOntology:Manufacturer',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Boeing_STU30',
    to: 'Boeing',
    label: 'AirportOntology:Manufacturer',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Boeing_UWD20',
    to: '1000',
    label: 'AirportOntology:MaximumSpeed',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'AirBus_SKU10',
    to: '900',
    label: 'AirportOntology:MaximumSpeed',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'AirBus_KMN20',
    to: '1000',
    label: 'AirportOntology:MaximumSpeed',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Boeing_STU30',
    to: '800',
    label: 'AirportOntology:MaximumSpeed',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_05C',
    to: 'Almaza_HELA',
    label: 'AirportOntology:GroundSurfaceIsPartOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_14D',
    to: 'Almaza_HELA',
    label: 'AirportOntology:GroundSurfaceIsPartOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_02E',
    to: 'Cairo_CAI',
    label: 'AirportOntology:GroundSurfaceIsPartOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_K',
    to: 'Cairo_CAI',
    label: 'AirportOntology:GroundSurfaceIsPartOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_B',
    to: 'Cairo_CAI',
    label: 'AirportOntology:GroundSurfaceIsPartOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_06D',
    to: 'Cairo_CAI',
    label: 'AirportOntology:GroundSurfaceIsPartOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_M',
    to: 'Almaza_HELA',
    label: 'AirportOntology:GroundSurfaceIsPartOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_05C',
    to: '05C',
    label: 'AirportOntology:GroundSurfaceName',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_A',
    to: 'A',
    label: 'AirportOntology:GroundSurfaceName',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_14D',
    to: '14D',
    label: 'AirportOntology:GroundSurfaceName',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_02E',
    to: '02E',
    label: 'AirportOntology:GroundSurfaceName',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_K',
    to: 'K',
    label: 'AirportOntology:GroundSurfaceName',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_B',
    to: 'B',
    label: 'AirportOntology:GroundSurfaceName',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_06D',
    to: '06D',
    label: 'AirportOntology:GroundSurfaceName',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_M',
    to: 'M',
    label: 'AirportOntology:GroundSurfaceName',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_A',
    to: 'Almaza_14D',
    label: 'AirportOntology:HasEntranceTo',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_K',
    to: 'Cairo_02E',
    label: 'AirportOntology:HasEntranceTo',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_B',
    to: 'Cairo_06D',
    label: 'AirportOntology:HasEntranceTo',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_M',
    to: 'Almaza_05C',
    label: 'AirportOntology:HasEntranceTo',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_A',
    to: 'open',
    label: 'AirportOntology:MaintenanceStatus',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_K',
    to: 'open',
    label: 'AirportOntology:MaintenanceStatus',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_B',
    to: 'locked',
    label: 'AirportOntology:MaintenanceStatus',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_M',
    to: 'locked',
    label: 'AirportOntology:MaintenanceStatus',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_05C',
    to: 'grass',
    label: 'AirportOntology:GroundType',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_14D',
    to: 'asphalt',
    label: 'AirportOntology:GroundType',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_02E',
    to: 'asphalt',
    label: 'AirportOntology:GroundType',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_06D',
    to: 'asphalt',
    label: 'AirportOntology:GroundType',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_05C',
    to: 'Almaza_M',
    label: 'AirportOntology:HasExitTo',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_14D',
    to: 'Almaza_A',
    label: 'AirportOntology:HasExitTo',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_06D',
    to: 'Cairo_B',
    label: 'AirportOntology:HasExitTo',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_05C',
    to: '1200',
    label: 'AirportOntology:Length',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_14D',
    to: '1500',
    label: 'AirportOntology:Length',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_02E',
    to: '2000',
    label: 'AirportOntology:Length',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_06D',
    to: '1200',
    label: 'AirportOntology:Length',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'GateIsPartOf',
    to: 'ConsistOfGate',
    label: 'owl:inverseOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'IsLocatedIn',
    to: 'LocationOf',
    label: 'owl:inverseOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'GroundSurfaceIsPartOf',
    to: 'ConsistOfGroundSurface',
    label: 'owl:inverseOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'HasEntranceTo',
    to: 'HasExitTo',
    label: 'owl:inverseOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'CairoInternationalAirport',
    to: 'Cairo_CAI',
    label: 'AirportOntology:Contain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'AlmazaAirport',
    to: 'Almaza_HELA',
    label: 'AirportOntology:Contain',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'CairoInternationalAirport',
    to: 'Cairo International Airport',
    label: 'AirportOntology:AirportName',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'AlmazaAirport',
    to: 'Almaza Airport',
    label: 'AirportOntology:AirportName',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_CAI',
    to: 'CAI',
    label: 'AirportOntology:AirfieldID',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_HELA',
    to: 'HELA',
    label: 'AirportOntology:AirfieldID',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Cairo_CAI',
    to: 'Cairo_C1',
    label: 'AirportOntology:ConsistOfGate',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_CAI',
    to: 'Cairo_B2',
    label: 'AirportOntology:ConsistOfGate',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_CAI',
    to: 'Cairo_B1',
    label: 'AirportOntology:ConsistOfGate',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_HELA',
    to: 'Almaza_A2',
    label: 'AirportOntology:ConsistOfGate',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_HELA',
    to: 'Almaza_A1',
    label: 'AirportOntology:ConsistOfGate',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_CAI',
    to: 'Cairo_02E',
    label: 'AirportOntology:ConsistOfGroundSurface',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_CAI',
    to: 'Cairo_K',
    label: 'AirportOntology:ConsistOfGroundSurface',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_CAI',
    to: 'Cairo_B',
    label: 'AirportOntology:ConsistOfGroundSurface',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_CAI',
    to: 'Cairo_06D',
    label: 'AirportOntology:ConsistOfGroundSurface',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_HELA',
    to: 'Almaza_05C',
    label: 'AirportOntology:ConsistOfGroundSurface',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_HELA',
    to: 'Almaza_14D',
    label: 'AirportOntology:ConsistOfGroundSurface',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_HELA',
    to: 'Almaza_M',
    label: 'AirportOntology:ConsistOfGroundSurface',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_CAI',
    to: 'civilian',
    label: 'AirportOntology:UsageType',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Almaza_HELA',
    to: 'military',
    label: 'AirportOntology:UsageType',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: 'Taxiway',
    to: 'GroundSurface',
    label: 'rdfs:subClassOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Runway',
    to: 'GroundSurface',
    label: 'rdfs:subClassOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: '_:96',
    to: 'asphalt',
    label: 'rdf:first',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: '_:99',
    to: 'grass',
    label: 'rdf:first',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: '_:118',
    to: 'locked',
    label: 'rdf:first',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: '_:119',
    to: 'open',
    label: 'rdf:first',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: '_:129',
    to: 'charter',
    label: 'rdf:first',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: '_:131',
    to: 'civilian',
    label: 'rdf:first',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: '_:133',
    to: 'military',
    label: 'rdf:first',
    arrows: 'from',
    filter: [ 'literal', 'resource' ] },
  { from: '_:96',
    to: '_:99',
    label: 'rdf:rest',
    arrows: 'from',
    filter: [ 'blanknode', 'resource' ] },
  { from: '_:99',
    to: 'nil',
    label: 'rdf:rest',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: '_:118',
    to: '_:119',
    label: 'rdf:rest',
    arrows: 'from',
    filter: [ 'blanknode', 'resource' ] },
  { from: '_:119',
    to: 'nil',
    label: 'rdf:rest',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: '_:129',
    to: '_:131',
    label: 'rdf:rest',
    arrows: 'from',
    filter: [ 'blanknode', 'resource' ] },
  { from: '_:131',
    to: '_:133',
    label: 'rdf:rest',
    arrows: 'from',
    filter: [ 'blanknode', 'resource' ] },
  { from: '_:133',
    to: 'nil',
    label: 'rdf:rest',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: '_:94',
    to: '_:96',
    label: 'owl:oneOf',
    arrows: 'from',
    filter: [ 'blanknode', 'resource' ] },
  { from: '_:117',
    to: '_:118',
    label: 'owl:oneOf',
    arrows: 'from',
    filter: [ 'blanknode', 'resource' ] },
  { from: '_:128',
    to: '_:129',
    label: 'owl:oneOf',
    arrows: 'from',
    filter: [ 'blanknode', 'resource' ] },
  { from: 'Almaza_05C',
    to: 'AirBus_SKU10',
    label: 'AirportOntology:LocationOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Almaza_05C',
    to: 'AirBus_KMN20',
    label: 'AirportOntology:LocationOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_K',
    to: 'Boeing_UWD20',
    label: 'AirportOntology:LocationOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Cairo_06D',
    to: 'Boeing_STU30',
    label: 'AirportOntology:LocationOf',
    arrows: 'from',
    filter: [ 'resource' ] },
  { from: 'Runway',
    to: 'Taxiway',
    label: 'owl:disjointWith',
    arrows: 'from',
    filter: [ 'resource' ] } ],
      nodes: [ { id: 'AirportOntology', label: 'AirportOntology' },
        { id: 'MaximumSpeed', label: 'MaximumSpeed' },
        { id: 'Elevation', label: 'Elevation' },
        { id: 'CompatibleAircraftType',
          label: 'CompatibleAircraftType' },
        { id: 'CompatibleWith', label: 'CompatibleWith' },
        { id: 'GateID', label: 'GateID' },
        { id: 'GatePassengerCapacity', label: 'GatePassengerCapacity' },
        { id: 'AircraftClass', label: 'AircraftClass' },
        { id: 'AircraftID', label: 'AircraftID' },
        { id: 'AircraftPassengerCapacity',
          label: 'AircraftPassengerCapacity' },
        { id: 'AircraftType', label: 'AircraftType' },
        { id: 'EngineCount', label: 'EngineCount' },
        { id: 'Manufacturer', label: 'Manufacturer' },
        { id: 'GroundSurfaceName', label: 'GroundSurfaceName' },
        { id: 'MaintenanceStatus', label: 'MaintenanceStatus' },
        { id: 'GroundType', label: 'GroundType' },
        { id: 'Length', label: 'Length' },
        { id: 'Contain', label: 'Contain' },
        { id: 'AirportName', label: 'AirportName' },
        { id: 'AirfieldID', label: 'AirfieldID' },
        { id: 'UsageType', label: 'UsageType' },
        { id: 'GateIsPartOf', label: 'GateIsPartOf' },
        { id: 'IsLocatedIn', label: 'IsLocatedIn' },
        { id: 'GroundSurfaceIsPartOf', label: 'GroundSurfaceIsPartOf' },
        { id: 'HasEntranceTo', label: 'HasEntranceTo' },
        { id: 'CairoInternationalAirport',
          label: 'CairoInternationalAirport' },
        { id: 'AlmazaAirport', label: 'AlmazaAirport' },
        { id: 'A2', label: 'A2' },
        { id: 'Ontology', label: 'Ontology' },
        { id: 'DatatypeProperty', label: 'DatatypeProperty' },
        { id: 'Class', label: 'Class' },
        { id: 'ObjectProperty', label: 'ObjectProperty' },
        { id: 'NamedIndividual', label: 'NamedIndividual' },
        { id: 'Datatype', label: 'Datatype' },
        { id: 'List', label: 'List' },
        { id: 'Airport', label: 'Airport' },
        { id: 'Runway', label: 'Runway' },
        { id: '_:117', label: '_:117' },
        { id: '_:94', label: '_:94' },
        { id: 'integer', label: 'integer' },
        { id: 'Airfield', label: 'Airfield' },
        { id: 'string', label: 'string' },
        { id: 'Gate', label: 'Gate' },
        { id: '_:128', label: '_:128' },
        { id: 'Aircraft', label: 'Aircraft' },
        { id: 'A320', label: 'A320' },
        { id: 'Boeing767', label: 'Boeing767' },
        { id: 'C1', label: 'C1' },
        { id: 'B2', label: 'B2' },
        { id: 'A1', label: 'A1' },
        { id: 'B1', label: 'B1' },
        { id: '350', label: '350' },
        { id: 'WideBody', label: 'WideBody' },
        { id: 'NarrowBody', label: 'NarrowBody' },
        { id: 'UWD20', label: 'UWD20' },
        { id: 'SKU10', label: 'SKU10' },
        { id: 'KMN20', label: 'KMN20' },
        { id: 'STU30', label: 'STU30' },
        { id: '100', label: '100' },
        { id: '200', label: '200' },
        { id: '300', label: '300' },
        { id: '150', label: '150' },
        { id: 'Boeing787', label: 'Boeing787' },
        { id: 'A330', label: 'A330' },
        { id: 'A380', label: 'A380' },
        { id: 'Boeing737', label: 'Boeing737' },
        { id: '4', label: '4' },
        { id: '2', label: '2' },
        { id: 'AirBus', label: 'AirBus' },
        { id: 'Boeing', label: 'Boeing' },
        { id: '900', label: '900' },
        { id: '1000', label: '1000' },
        { id: '800', label: '800' },
        { id: '05C', label: '05C' },
        { id: 'A', label: 'A' },
        { id: '14D', label: '14D' },
        { id: '02E', label: '02E' },
        { id: 'K', label: 'K' },
        { id: 'B', label: 'B' },
        { id: '06D', label: '06D' },
        { id: 'M', label: 'M' },
        { id: 'Almaza_A', label: 'Almaza_A' },
        { id: '1500', label: '1500' },
        { id: '2000', label: '2000' },
        { id: '1200', label: '1200' },
        { id: 'ConsistOfGate', label: 'ConsistOfGate' },
        { id: 'LocationOf', label: 'LocationOf' },
        { id: 'ConsistOfGroundSurface',
          label: 'ConsistOfGroundSurface' },
        { id: 'HasExitTo', label: 'HasExitTo' },
        { id: 'Cairo_CAI', label: 'Cairo_CAI' },
        { id: 'Almaza_HELA', label: 'Almaza_HELA' },
        { id: 'Cairo International Airport',
          label: 'Cairo International Airport' },
        { id: 'Almaza Airport', label: 'Almaza Airport' },
        { id: 'CAI', label: 'CAI' },
        { id: 'HELA', label: 'HELA' },
        { id: 'Cairo_C1', label: 'Cairo_C1' },
        { id: 'Cairo_B2', label: 'Cairo_B2' },
        { id: 'Cairo_B1', label: 'Cairo_B1' },
        { id: 'Almaza_A2', label: 'Almaza_A2' },
        { id: 'Almaza_A1', label: 'Almaza_A1' },
        { id: 'Cairo_02E', label: 'Cairo_02E' },
        { id: 'Cairo_K', label: 'Cairo_K' },
        { id: 'Cairo_B', label: 'Cairo_B' },
        { id: 'Cairo_06D', label: 'Cairo_06D' },
        { id: 'Almaza_05C', label: 'Almaza_05C' },
        { id: 'Almaza_14D', label: 'Almaza_14D' },
        { id: 'Almaza_M', label: 'Almaza_M' },
        { id: 'GroundSurface', label: 'GroundSurface' },
        { id: 'asphalt', label: 'asphalt' },
        { id: 'grass', label: 'grass' },
        { id: 'locked', label: 'locked' },
        { id: 'open', label: 'open' },
        { id: 'charter', label: 'charter' },
        { id: 'civilian', label: 'civilian' },
        { id: 'military', label: 'military' },
        { id: '_:99', label: '_:99' },
        { id: '_:119', label: '_:119' },
        { id: '_:131', label: '_:131' },
        { id: '_:133', label: '_:133' },
        { id: 'nil', label: 'nil' },
        { id: '_:96', label: '_:96' },
        { id: '_:118', label: '_:118' },
        { id: '_:129', label: '_:129' },
        { id: 'AirBus_SKU10', label: 'AirBus_SKU10' },
        { id: 'AirBus_KMN20', label: 'AirBus_KMN20' },
        { id: 'Boeing_UWD20', label: 'Boeing_UWD20' },
        { id: 'Boeing_STU30', label: 'Boeing_STU30' },
        { id: 'Taxiway', label: 'Taxiway' } ]

    };
    return textExample;
  };

  handleVisualize = () => {
    console.log('initialize app attempt');
    console.log('finish handleVisualize');
  };

  render() {
    console.log('start render add css');
    const file = this.fetchFile();
    console.log('finish add css');
    return (
      <div className="visualize-container">
        <button className="btn btn-success"
                style={{marginLeft: 50}}
                onClick={this.handleVisualize.bind(this)}>
          Visualize</button>
          <Graph graph={file}/>
       </div>
    );
  }
}
